pipeline {                                                                                                       
     agent {
        docker {
          image 'node:10.11.0-alpine'
        }
     }
     stages {
        stage ("Build") {
           steps {
              export PATH=/usr/share/npm
              sh "npm install"
           }
        }
     }
  }
